services:
  - type: web
    name: face-sorter
    runtime: image
    image:
      url: docker.io/vatpham/face-sorter:latest
    envVars:
      - key: FLASK_SECRET_KEY
        sync: false
      - key: PORT
        value: 5000
